name: demo workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: message
        run: echo "CI Pipeline Running"
      
      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: check java version 
        run: java --version
